### ISSUE TITLE
Let's polish this up for a release?

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/brave-karaf#4]
Let's polish this up, move it up to latest brave and to zipkin2 reporter. It hasn't been released before, so seems a good time.

**Comment by codefromthecrypt** [comment]
https://github.com/openzipkin/brave-karaf/pull/5

**Comment by codefromthecrypt** [comment]
ok we are just about ready.. I think just circleci needs credentials re-encrypted

tried release-0.1.0 and it failed due to this

**Comment by codefromthecrypt** [comment]
attempting a release based on dubbo's guide https://dubbo.incubator.apache.org/en-us/blog/prepare-an-apache-release.html

**Comment by codefromthecrypt** [comment]
https://lists.apache.org/thread.html/04ab2034ce82d9539e48530cb683cd46651a1795a1ed3ff8827118fb@%3Cdev.zipkin.apache.org%3E


@reta question for you.. I released like this.

```bash
./mvnw release:prepare -Prelease -Darguments="-Dmaven.test.skip=true" -DautoVersionSubmodules=true -Dusername=adriancole -DpushChanges=false
./mvnw release:perform -Prelease -pl -:brave-itests -Darguments="-Dmaven.test.skip=true" -DautoVersionSubmodules=true -Dusername=adriancole
```

I noticed that eventhough I put a skip in, itests still uploaded. Maybe we need to add a skip to the pom directly?

```
[INFO] Uploading to apache.releases.https: https://repository.apache.org/service/local/staging/deploy/maven2/org/apache/zipkin/brave/karaf/brave-itests/0.1.2/brave-itests-0.1.2.jar.asc
```

**Comment by reta** [comment]
Good question, @adriancole , I think you need to skip inside the `pom.xml` direcly for `brave-itests`, as you suggested:

```
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-deploy-plugin</artifactId>
    <configuration>
        <skip>true</skip>
    </configuration>
  </plugin>
```

Could you please try it out? As a side note, many projects publish all artifacts, seems to be easier :)

**Comment by codefromthecrypt** [comment]
heh cool. I will work this in tomorrow morning

**Comment by codefromthecrypt** [comment]
I left an old "release" profile in the build, and used that instead of the apache one. That's why there was no asc file @abesto 

Here's the commands I used to release this time:
```bash
$ ./mvnw release:prepare -Papache-release -Darguments="-Dmaven.test.skip=true" -DautoVersionSubmodules=true -Dusername=adriancole -DpushChanges=false
$ ./mvnw release:perform -Papache-release -Darguments="-Dmaven.test.skip=true" -DautoVersionSubmodules=true -Dusername=adriancole
```
